### ISSUE TITLE
Frame drops when scrolling

### ISSUE THREAD

**Issue by VandeurenGlenn** [PolymerElements/iron-scroll-target-behavior#18]
### Description

Frame drops when scrolling
### Expected

![expected](https://cloud.githubusercontent.com/assets/8685280/15876044/49b95370-2d0b-11e6-949d-b14f7bb06510.png)
### Actual

![actual](https://cloud.githubusercontent.com/assets/8685280/15876122/bf7df796-2d0b-11e6-9612-76fe346fb532.png)
### Fix

requestAnimationFrame

**Comment by blasten** [comment]
@VandeurenGlenn How are you using this behavior? I was looking at your commit, but I don't think that would work.

**Comment by VandeurenGlenn** [comment]
@blasten I was checking out [App drawer template](https://www.polymer-project.org/1.0/toolbox/templates) and noticed drops.
After the PR was made I realized it wasn't going to work, although when I was checking before,  the drops were away & there were no errors, butt I probably didn't forget to bind 'this' back then 😄, I'll check App drawer template again soon to find out if using 'requestAnimationFrame' is going to work or not.

**Comment by blasten** [comment]
The answer to this problem is complicated. @justinfagnani had a request for async layout to avoid layout trashing, but without a standard and browser support, this problem would remain unsolved. I'd recommend reading this article http://wilsonpage.co.uk/preventing-layout-thrashing/ or checking out FastDOM on GitHub.
